application:
  env:
    name: prod

pom:
  version: @project.version@ # need lombok

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: "info, health, loggers, env"
      base-path: /actuator

  endpoint:
    health:
      show-details: always


spring:
  datasource:
    url: jdbc:mysql://34.39.2.90:6033/demo_cloud_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: cloud_user
    password: ENC(ymuuQMXfXKmhx0/6Bmfk1Wgm0fNLGqUiesDBI+TvZvJZqIqc9YwsYovwE75CF6An)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 30000
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      org:
        hibernate:
          envers:
            audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy
            audit_strategy_validity_store_revend_timestamp: true

jasypt:
  encryptor:
    # algorithm of encryption
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # salt for encryption
    # how to avoid to expose the salt in the code?
    # https://blog.csdn.net/qq_26878363/article/details/103731173
    password: jaspyt_password